spring:
  jackson:
    # deserialization 에서 변환할 수 없는 포맷의 데이터일 경우 error 를 반환하도록 설정
    # spring 에서 error를 catch하면 기본적으로 해당 API 는 bad request 응답을 반환한다
    deserialization.fail-on-unknown-properties: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true

logging:
  level:
#    org.springframework.security: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace

my-app:
  admin-username: admin@email.com
  admin-password: admin
  user-username: user@email.com
  user-password: user
  client-id: myApp
  client-secret: pass
